//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease_Symptom_rel
    {
        public int disease_id { get; set; }
        public int symptom_id { get; set; }
        public string scores { get; set; }
        public Nullable<int> type { get; set; }
    }
}
