//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modeler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Survey
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string gender { get; set; }
        public double lambda { get; set; }
        public double HR { get; set; }
        public double v { get; set; }
    }
}
