//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modeler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int symptom_id { get; set; }
        public string symptom_name { get; set; }
    }
}
